# -*- coding: utf-8 -*-
"""Копия блокнота "tuples, sets, dicts.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oYYfF_0ZpHnU3G_QurPDaW1ugER6e1Pc

*Сегодня мы поговорим о новых типах данных: кортежах, множествах и словарях*

##**Кортеж (tuple)**

это неизменяемый список.

Зачем нужны кортежи, если есть списки?

    1. Защита данных. Кортеж защищен от изменений, как намеренных (что плохо), так и случайных (что хорошо).
    2. Меньший размер. Вам нужно меньше памяти, чтобы хранить данные
"""

# сравним размеры

a = (1, 2, 3, 4, 5, 6) # кортеж
b = [1, 2, 3, 4, 5, 6] # лист/список

print("\nSize of the tuple: ",a.__sizeof__(),"\nsize of the list: ",b.__sizeof__()) 

# если вы не понимаете, что происходит в этой ячейке, не переживайте: метод .__sizeof__() пока можно воспринимать как асбтракцию

"""Как работать с кортежами? Примерно так же, как и со списками. Давайте создадим кортеж: 

    1. С помощью встроенной функции tuple()
"""

a = tuple() 
print(a, "\n",type(a))

"""2. С помощью литерала кортежа ()"""

b = ()
print(b, "\n",type(b))

"""Создаем кортеж из одного элемента:"""

a = ('sljbglb ;k')
print(a, "\n",type(a))
# проверим его тип

"""Получилась строка :(  
    
А как получить кортеж?
"""

a = ('sljbglb ;k', ) # все дело в запятой! 

print(a, "\n",type(a))
# проверим тип

"""3. и еще один способ задать кортеж:"""

a = 's',
a

"""создать кортеж из итерируемого объекта можно с помощью функции tuple()"""

a = tuple('hello')
a

"""###Операции с кортежами

кортежам доступны все операции над списками, не изменяющие список: сложение, умножение на число, методы index() и count()), можно работать с индексами и так далее.

##**Множество (set)**

это тоже "контейнер" для данных, но в отличие от листа(списка), он содержит уникальные, не повторяющиеся элементы.

Давайте создадим множество:

    1. с помощью функуии set()
"""

set("heLlo")

fruits = ["apples","peaches","cherries","pears","oranges","persimmons"] # задали список, сохранили в переменную
#  проверим его тип:
print(type(fruits)) # list
# давайте изменим тип на set с помощью функции set()

fruits = set(fruits) #применили функцию, пересохранили переменную

#проверим ее тип еще раз 
print(type(fruits)) # set 

type(fruits)

"""2. с помощью литерала {}"""

new_set = {2,5.9,"apples", False}  # создали переменную, сложили в нее некоторые объекты
# можем складывать в множество объекты разных типов: числовые, строковые, логические

# давайте проверим, что new_set действительно множество
print(type(new_set))

"""NB! обратите внимание, что в отличие от листа, множество нельзя задать пустым литералом и что-то в него добавлять"""

another_set = {} # создали пустое....

# ....множество? Давайте проверим тип созданной переменной 

print(type(another_set)) 

""" это не множество, это словарь! (о них мы поговорим позже). 
Давайте пока запомним главное: множества не задаются пустыми литералами """

"""Множества удобно использовать для удаления повторяющихся элементов:"""

cars = ["BMW","Toyota","Bentley","Jeep","Jeep"]
cars = set(cars)
cars

"""операции со множествами"""

#число элементов в множестве (размер множества).
len(cars)

# x in s - принадлежит ли x множеству s. Возвращает True/False

"Kia" in cars
# "Jeep" in cars

"""И операции, изменяющие множество:"""

#добавляем элемент в множество
#elem = 
cars.add("VolskWagen")
cars

# добавляем множество во множество
french_cars = {"Peugeot", "Citroën", "Renault"}
cars.update(french_cars)
cars

# удаляем элемент из множества. 
cars.remove("Jeep")
cars

# KeyError, если такого элемента не существует.
cars.remove("Lamborgini")

cars.discard("Lamborgini") # удаляет элемент, если он находится в множестве.
# Если элемента нет, не поднимает ошибку

# удаляет первый элемент
print(cars)
cars.pop()

# запустите несколько раз, посмотрите на результат

# очищаем множество

cars.clear()
cars

"""математические операции со множествами"""

fruits # возьмем наше множество фруктов

berries = {"strawberry", "red currant"}
fruits.isdisjoint(berries) # True, если множества  не имеют общих элементов.

fruits == berries
 # True если все элементы set принадлежат other,
 # все элементы other принадлежат set.

#berries.issubset(fruits) # является ли подмножеством
 french_cars  <= cars
# fruits <= berries # True если все элементы berries принадлежат fruits.

#fruits.issuperset(berries) # аналогично, но в обратную сторону
# berries >= fruits
   cars >= french_cars

fruits.union(berries) # объединение нескольких множеств 
# fruits | berries

#  пересечение множеств 
 # пустое, у них нет общих элементов

# давайте добавим арбуз 

fruits.add("watermelon")
berries.add("watermelon")

fruits.intersection(berries)

# fruits & berries

"""### еще один вид множества - frozenset

    set изменяемый, frozenset - нет
"""

a = set("random")
b = frozenset('Random')
a == b # давайте сравним множества

a.add(1) #добавим элемент в первое множество
a

b.add(2)
# мы не можем добавлять в frozenset

"""##**Словарь (dict)**

коллекции произвольных объектов, записанные в виде *ключ : значение*
(ключи уникальные, значения могут повторяться)

( словари =ассоциативные массивы = хеш-таблицы)


Давайте создадим словарь:

    1. С помощью литерала:
"""

d = {}
d

d = {'Jane': "London", 'Olga': "Moscow"} 
# Jane, Olga - это ключи, London, Moscow - значения
d

"""2.  с помощью функции dict()"""

d = dict(short='dict', long='dictionary')
d

"""3. с помощью генераторов словарей (почти как генераторы списков)"""

d = {a: a ** 2 for a in range(7)}
d

"""##с помощью метода fromkeys:"""

d = dict.fromkeys(['a', 'b'])
d

d = dict.fromkeys(['a', 'b'], 100)
d

"""###Теперь попробуем добавить записей в словарь и извлечь значения ключей

извлекается синтаксисом: название_переменной_словаря[ключ]
"""

d = {1: 2, 2: 4, 3: 9}
d[4] # достаем значение по ключу 1

d[3] = 4 ** 2 # добавляем пару, где ключ =4, а значение = 4**2
d # посмотрим на весь словарь

d = {}

# попробуем достать ключ, которого нет
d[5]

"""**Итог:** присвоение по новому ключу расширяет словарь, присвоение по существующему ключу перезаписывает его, а попытка извлечения несуществующего ключа порождает исключение.

###методы словарей
"""

d = {'Jane': "London", 'Olga': "Moscow","Paul":"Paris","Ivan":"Minsk","Anne":"Copenhagen"}

d.values() # возвращает значения в словаре

d.keys() # возвращает ключи в словаре

d.items() # возвращает пары (ключ, значение)

new_dict = {"Alexander":"Bonn", "Julia":"Madrid"}
d.update(new_dict) # обновляет словарь, добавляя пары (ключ, значение) из other. Существующие ключи перезаписываются. Возвращает None (не новый словарь!)
d

d.pop("Julia") # удаляет ключ и возвращает значение. Если ключа нет, возвращает default (по умолчанию бросает исключение).
d

d.popitem() # удаляет и возвращает пару (ключ, значение)

d.get("Jane") #выдает значение по ключу, ключ в скобках

! python3

d.clear() # очищает словарь
d

"""**C кортежами, списками, словарями и множествами можно использовать циклы for и while**

###classwork


Определяем лучшего писателя отзывов. 
У вас есть четрые отзыва на фильм С.Кубрика "Сияние". Вам нужно определить, кто из авторов отзывов обладает наиболее развитым лексиконом ( таковым считаем самый длинный набор неповторяющихся слов в пределах одного отзыва). 
    для определения вам нужно: 

    1. Предобработать строку (см методы строк), сведя все к нижнему регистру, убрать пунктуацию.

    2. Превратить строку в список 
    3. определить уникальные элементы в списке (надо что-то сделать со списком)
    4. определить размер уникальных слов в пределах автора
    5. определить наилучшего
"""

paul = """When this film first came out in 1980, I remember going to see it on opening night. 
This movie just scared the life out of me, which is what still happens every time
I rent the video for a re-watch.I have seen The Shining at least six or seven times, and I still
believe it to be simultaneously and paradoxically one of the most frightening and yet funniest
films I've ever seen. Frightening because of the extraordinarily effective use of long shots
to create feelings of isolation, convex lens shots to enhance surrealism, and meticulously scored
music to bring tension levels to virtually unbearable levels. And \"funny\" because of Jack
Nicholson's outrageous and in many cases ad-libbed onscreen antics. It never ceases to amaze me
how The Shining is actually two films in one, both a comedy AND a horror flick. Ghostly 
apparitions of a strikingly menacing nature haunt much of the first half of the film, which
gradually evolve into ever more serious physical threats as time progresses. Be that as it may,
there is surprisingly little violence given the apparent intensity, but that is little comfort 
for the feint of heart as much of the terror is more implied than manifest. The Shining is a truly
frightening movie that works symbolically on many levels, but is basically  about human 
shortcomings and the way they can be exploited by unconscious forces combined with weakness
of will. This film scares the most just by using suggestion to turn your own imagination against
you. The Shining is a brilliant cinematic masterpiece, the likes of which have never been seen
before or since. Highly, highly recommended."""

jane = """Chilling, majestic piece of cinematic fright, this film combines all the great elements
of an intellectual thriller, with the grand vision of a director who has the instinctual capacity to pace a
moody horror flick within the realm of his filmmaking genius that includes an eye for the original shot, 
an ice-cold soundtrack and an overall sense of dehumanization. This movie cuts through all the typical horror
movies like a red-poker through a human eye, as it allows the viewer to not only feel the violence and psychosis of
its protagonist, but appreciate the seed from which the derangement stems. One of the scariest things for people
to face is the unknown and this film presents its plotting with just that thought in mind. The setting is perfect,
in a desolate winter hideaway. The quietness of the moment is a character in itself, as the fermenting aggressor
in Jack Torrance's mind wallows in this idle time, and breeds the devil's new playground. I always felt like the
presence of evil was dormant in all of our minds, with only the circumstances of the moment, and the reasons given
therein, needed to wake its violent ass and pounce over its unsuspecting victims. This film is a perfect example 
of this very thought."""

kate = """What can I say about the scariest movie I have ever seen that has not already been said by others more
articulate than yours truly? Do not view this film expecting to see a screen version of the Stephen King novel.
Rather, this is a Stanley Kubrick film, and to fully appreciate it one should judge it within the context of
Kubrick's entire body of work as a serious filmmaker. Thematically, THE SHINING relates most closely to 2001:
A SPACE ODYSSEY, though flourishes of PATHS OF GLORY, A CLOCKWORK ORANGE and BARRY LYNDON do manage to
figure prominently in the film's overall technique. In a nutshell (no pun intended), Jack Nicholson and Shelly
Duvall co-star with Oregon's Timberline Lodge - enlisted to portray the exterior of the Overlook Hotel - in a
story that appears on the surface to be about ghosts and insanity, but deals with issues of child abuse, 
immortality and duality. What the film might lack initially in terms of coherence is more than made up for in
technique. Garrett Brown (the male voice in those old Molson Golden commercials), inventor of the Steadicam,
chases young Danny Lloyd through hotel corridors and an amazing snow maze, providing magic-carpet-ride fluidity
to scenes that ten years earlier would have been impossible to accomplish. If the film starts off too slow,
remember who the director is. This man likes to take his time, and the results are well worth it: incredible
aerial shots of the Overlook Hotel; horrific Diane Arbus-inspired twins staring directly at us; portentous room 237
and its treasure trove of terrible secrets; elevators that gush rivers of blood in slow-motion; Jack Torrance's
immortality found via the hotel (akin to David Bowman's journey through the Space Gate); and some of the best use
of pre-existing music ever assembled for a motion picture."""


nick = """I was never a big fan of horror movies. They usually try cheap tricks to scare their audiences like loud
noises and creepy children. They usually lack originality and contain overacting galore. The only horror movie i
like was Stir of Echoes with Kevin Bacon. It was well-acted, and had a great story. But it has been joined and
maybe even surpassed by Stanley Kubrick's The Shining, quite possibly the scariest movie ever. The movie follows
a writer (Jack Nicholson) and his family who agree to watch over a hotel while it is closed for the winter.
There were rumors of the place being haunted and the last resident went crazy and murdered his family. But Jack is
convinced it will be OK and he can use the quiet to overcome his writer's block. After months of solitude and
silence however, Jack becomes a grumpy and later violent. Is it cabin fever or is there something in the hotel
that is driving him mad? One of the creepiest parts about the movie is the feeling of isolation that Kubrick makes.
The hotel is very silent, and the rooms are huge, yet always empty. It is also eerily calm when Jack's son
is riding his bike through the barren hallways. Jack Nicholson's performance is also one of his very best, scaring
the hell out of me and making me sure to get out once in awhile. My favorite scene is when he is talking to a ghost
from inside a walk-in refrigerator. The Shining is tops for horror movies in my opinion, beating the snot out
of crap like the Ring and The Blair Witch Project. It may be a oldie, but is definitely a goodie."""

"""##homework

с помощью словаря создайте простой транслитератор: нужно, чтобы программа принимала с клавиатуры (у нас есть специальный оператор ввода с клавиатуры) слова, записанные кириллицей, и печатала результат латиницей. 

Пример: *собака >> sobaka*
"""

